### ISSUE TITLE
Your aws access and secret keys are visible...

### ISSUE THREAD

**Issue by hickeroar** [henrikolsson/hotslogs-uploader#1]
https://github.com/henrikolsson/hotslogs-uploader/blob/master/src/hotslogs/core.clj#L13

Someone could mess with anything in your aws account that the key has access to. S3 supports "presigned urls" which would be a much more secure way to get users to upload files. It was designed for this scenario. :-)

**Comment by henrikolsson** [comment]
Hi, thanks for the interest :) 

I found these by looking at how the official uploader works. I emailed the hotslogs author about this and he said it was fine to share the keys since they only allow uploads.

Perhaps you should contact him to discuss it? :)
Contact info at https://www.hotslogs.com/Info/About

**Comment by hickeroar** [comment]
Ah. Still seems like someone could upload 500TB of random junk and drive his bill sky-high, or start using his account to host their own files. I doubt amazon would refund it either since he made the keys public. :P

If they're not yours I can't fault you, but it definitely isn't a good practice for key owners to make them public (this is why amazon won't even show you your secret more than 1 time when you make it).
